apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-with-sc
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
