apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nginx
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions: 
  - discard
volumeBindingMode: WaitForFirstConsumer
parameters: 
  guarenteedReadWriteLatency: "true"