global:
  # scrape_interval: "30s"
  # scrape_timeout: "10s"
  # evaluation_interval: "35s"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - 127.0.1.1:9090
        labels:
          env: production
    relabel_configs:
      - source_labels:
        - 'env'
        regex: (production)
        replacement: 'isidore'
        action: replace
        target_label: 'env'

  - job_name: gulfcam_backend
    static_configs:
      - targets:
          - 192.168.1.240:8084

  - job_name: postgres
    scrape_timeout: 1m
    scrape_interval: 1m
    static_configs:
      - targets:
          - 192.168.1.240:5432
    metrics_path: /probe
    params:
      auth_module: [foo]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels:
          - __address__
        target_label: __address__
        replacement: 192.168.1.240:9187

  - job_name: 'prometheus-test'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{instance="34.86.5.170:9090",  job="prometheus-test"}'
    static_configs:
      - targets:
        - '34.86.5.170:9090'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 192.168.1.240:9093 

rule_files:
  - "prometheus_rules.yml"
  