apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions: 
  - discard
volumeBindingMode: Immediate
parameters: 
  guarenteedReadWriteLatency: "true"