apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: dev-deployment-reader
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "pods",]
  verbs: ["get", "watch", "list", create]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-deployments
  namespace: default
subjects:
- kind: ServiceAccount
  name: isidore-sa 
  namespace: default
  #apiGroup: ""
roleRef:
  kind: Role 
  name: dev-deployment-reader 
  apiGroup: rbac.authorization.k8s.io
  