apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- nginx-secret.yaml
components:
- ../components/
namePrefix: "dev-"
# patches:
#   - path: nginx-deployment.yaml
configMapGenerator: 
- name: my-config
  files:
  - index.html

# configurations: 
# - namereference.yaml
